# Site settings
title: Madeira
locale: uk
partner:
  name: Madeira Regional Tourism Board
  link: "http://www.visitmadeira.pt"

description: >
  Madeira is an enchanting archipelago, a cluster of islands just off the northwest coast of Africa where a mild, year-round Mediterranean climate offers the perfect winter-sun escape. Between Madeira, Porto Santo, Ilhas Desertas and Ilhas Selvagens, discover remarkable outdoor scenes, from beautiful coastlines to wild nature, and sink into the unique lifestyle of this charming island chain.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/madeira" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/madeira/_assets/img"
css:     "/uk/2020/madeira/_assets/css"
js:      "/uk/2020/madeira/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed